version: "3"
services: 
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/frontend/ #ro means docker can't change any of these files
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
    # env_file: 
    #   - ./.env
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=rasim
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=frontendb
    
    networks:
      - deploy_network

    container_name: backend

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - 8501:8501
    volumes:
      - ./:/usr/src/frontend/
    # environment:
    #   - BACKEND_URL=http://localhost:8000
    networks:
      - deploy_network

    container_name: frontend
  
  postgres:
    image: postgres
    expose:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=rasim
      - POSTGRES_DB=frontendb
    
    networks:
      - deploy_network

    volumes:
      - postgres-db:/var/lib/postgresql/data
    


networks:
  deploy_network:
    driver: bridge

volumes:
  postgres-db:
  frontend:
    
